kind: Secret
apiVersion: v1
metadata:
  name: docker-auth-secret 
type: Opaque
stringData:
  config.json: | #base64 value of  id:password is being used below.
    {
    	"auths": {
    		"https://index.docker.io/v1/": {
    			"auth": "cHJpeWFkZXZkb2M6UHJpeWFAMTIz" 
    		}
    	}
    }
