apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: func-test-build-deploy-pipeline-run- #generate dynamic names for pipelinerun
  namespace: default
spec:
  pipelineRef:
    name: func-test-build-deploy-pipeline
  serviceAccountName: dockerconfig 
  workspaces:
  - name: sources
    persistentVolumeClaim:
      claimName: source-pvc
    subPath: source
  - name: gitconfig
    secret:
      secretName: my-basic-auth-secret   
status: {}
