apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: func-test-build-deploy-pipeline
  annotations:
    description: |
      Build the a `func` project and deploys it to the cluster
spec:
  params:
    - name: gitRepo
      description: The git repository that hosts the project
      default: http://10.8.30.54:81/priya.kumari/project1.git
    - name: gitRevision
      description: The git revision to build
      default: master
    - name: kind
      description: resource kind
      default: Pod
    - name: IMAGE_REPO
      description: Image repository name
      default: priyadevdoc
    - name: IMAGE_NAME
      description: The name of the built container image. 
      default: test_image
    - name: IMAGE_TAG
      description: The tag of the built container image. 
      default: v1
  workspaces:
    - name: sources
      description: Workspace where the git repo is prepared for building
    - name: gitconfig
      description: Workspace where git secret is stored
    - name: dockerconfig
      description: workspace where docker secret is stored
    - name: shared-workspace
      description: workspace containing kube config files
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
        bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.5
      params:
        - name: url
          value: $(params.gitRepo)
        - name: revision
          value: $(params.gitRevision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: sources
        - name: basic-auth
          workspace: gitconfig
    - name: modify-permission
      runAfter: [clone-repo]
      taskRef:
        name: modify-permission
      params:
        - name: path
          value: "."
        - name: permission-level
          value: "777"
      workspaces:
        - name: output
          workspace: sources
    - name: source-to-image
      runAfter: [modify-permission]
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: priyadevdoc/test_image:v1
        - name: EXTRA_ARGS
          value: 
            - --skip-tls-verify
      workspaces:
        - name: source
          workspace: sources
        - name: dockerconfig
          workspace: dockerconfig
    - name: yaml-replace
      runAfter: [source-to-image]
      taskRef:
        name: yq
      workspaces:
        - name: source
          workspace: sources
      params:
        - name: files
          value:
          - "./artifacts/deployment.yaml"
        - name: expression
          value: '.spec.template.spec.containers[0].image=\""$(params.IMAGE_REPO)\/$(params.IMAGE_NAME):$(params.IMAGE_TAG)@$(tasks.source-to-image.results.IMAGE-DIGEST)"\"'
    - name: display-results
      runAfter: [yaml-replace]
      workspaces:
        - name: source
          workspace: sources
      taskSpec:
        workspaces:
        - name: source
        steps:
          - name: print
            image: docker.io/library/bash:5.1.4@sha256:b208215a4655538be652b2769d82e576bc4d0a2bb132144c060efc5be8c3f5d6
            script: |
              #!/usr/bin/env bash
              set -e
              cat $(workspaces.source.path)/artifacts/deployment.yaml
    - name: create-config
      runAfter: [yaml-replace]
      taskRef:
        name: kubeconfig-creator
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: name
          value: cluster.local
        - name: username
          value: kubernetes-admin
        - name: url
          value: https://10.8.30.3:6443
        - name: cadata
          value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ETXlOVEExTkRBME0xb1hEVE14TURNeU16QTFOREEwTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjlsCjM2MFVKaGZXVk4wTFZwVXJpd280K0hLc1dtNXhlbUJtUXFlU3NZK0R6Zmg3Wi9kbkVyYTdOcFUyWXQ3eWxHSGMKYzd3RTdsZ1hFL0VNZDJvZllYeXoyVERmT3RhRUFWWXV2M0wvQ2QxVUJuakJHN21iMWJBY1RWa3JHR0hLWDJ2SAo0NWpXWnVaMHpreVIvZ2V0NUlONGJhSmFpeE9GNDhRVU9CVEQ5SWVaWWZUMll3Qmgzd3U3TmJrak1nOUxwQVkvCjczNDJ5VENqUW5hNjNqYWJndHR0RjJVUUkxQnVvaVl1QzIwa3F1M0JmelBpTEZJdUtsQmw5S09lekd3Wno5VmYKZkNjTTVxbEZwdkl0SUJxSzkyVlB6SmJCTkYxbmlxNXBDOG15VDRyYk40NnY3QTFydVg5ZjRlcHNMM2Z1ckVNVApwYVNIdmdwZUJGa1ovL3Y0ZTAwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZOMGVUdVhuT3VzM0gzSVVTTk53NmtvT3VzTWlNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBSExFWnRWR1hMTkM1T2d2RmpFN0NmRnNCWTVueHJ4NzRBc1dqSWJ4Q1JVdHhKbVJDTAp6Y2c0akhZeFBaTGYvcUNGQUJGbmZjeTJleC9IYW1iNU00Q0dSMENxaE13UnhISGNkQm9tVUZhZmRJellreDRrCkVLRFUrUWRTait6QmFBUzJadEJMQWhuYit0OTlzVkpTdTlyaW9UZklmUXIxNU5jVkoxNVVJVEJqTzZhdHF6WkgKKzJLRVNmeXdDN092eGdQK0xuWEpVOTc5TlNHaGNWdkdLRG96UmdPVnBOZkdlbkUwMll1Sll0QTlSMTJzazhyMQprTTA4cWZJdmppMysyT2FmSS92bmlEY3RUNU1vQThtNzlvWG9DRXlRdkxsT1JiZXB1SWw4aHNldUZlRVd3V0VWCnlLd3lWMWFXMTBJcUprNFdBUDgzeU9Zc0hYVWpmc0c5Q1pkSwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        - name: clientKeyData
          value: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcFlPcUFaQ2hoR3paTEJyQU1QakwvVmZvclljYlh5UHd6TU1ISzNYVUFPTzBKNnB2CmhqM09Zd3FMOVdPLzhGalduNUJaK1hOa1VBbWpxKzF0R0E2bUJKZEdxaTdSdUNHem9Pc09uRDRiRmpYNUZZOHQKdWxlVndxVUJQNHEvMXY5RlRWaCtMODZrSktkTnRIRmtpcitBTG1vWHdycGR4R2RzNTJhUHprNWhBQk9DZG8zdgo1bm0xSVpzZ0ZGZWU5OFp5RERpTHBjYm9HRndFRXhpRThuTGFEYXdqTEEzbUs4LzFpWXkwV1BtckRHMys3alhVCjZGcWxoaEMwT1hTUEdqa0U4ZURQeTBRNXJpTGJlNENjWjNpeERpNWpHTHpBUWJFRTVNcXJzNU5DUmNObkNoVWIKek5VRVhHNlRCYnhhYnRoWlQ1YUZlR2ZIbjR5N3hFa0wvcjZmQ1FJREFRQUJBb0lCQUJaSEMzbmNjckQxU2FIVApFKzFEZjRsZzdMTjJqT3VZVmMvcHJDeGdWcUdzQkZLV2NSNWJjVTBKWFY4eEJ1T2R3WDJHbTJXazcycUtjWm94CmdjNk1JakpaL2l2bjAxaDZTTWd1K3k5eWVJamJ5T1BxK3Blck5FQVhuM3hpKzRFL3FKOUpldXFLWUxPQ1JVWTEKUVBnZjRHdmU0Y1hXK2NuMnRjVExuQzJEaFREU04vMHNaT0syQ3lmT09IbENSQ3pjRFUrcUpac2ZXU0V6M3lZNgpTdmVueXM5Vkp5c2FKZG9GY09VTEpyMnhTeGVRMnV6VlV1ZkxrcHpqR09tdkhDa1R0R21pL2Z3VXhEQVBVa094CjNqUVBObGdlWExqTmNUelZMem94MFJ0WDRSMUxZWHIyeXE4TE5STWhxeHFyeERrWm00RzhSQjhsaU5XVHQrekcKVWRwQVV4RUNnWUVBMDZESnI5YTd2aURuVHF4dzZPeEhtZk1JOCtnZ25qb01qOGJ0ZldFZE91MERXbjhnd2FPSwpxZ1pCSmZSNENlcHFYeTVCY1pQWjRRZVkrZk1lbXUwVGh1N05LWlJ1eFRrSXNFV3p0bDNBdFRRbVRYQ2krMUliCmJFbmswcHAyMnlqTjdTNk02YXRXTnpsOHNiZENYTGluaDdzV3FudjdLaW5ZQjZvdVA5Umsza1VDZ1lFQXlEZTAKSE13UXkranpxRk9KR29zUmJYTzRYU3JVa2gzSDJ0dHZaaDhybGJFaFUwYUhYWGZISStuTVhFNUdXQzB3WStNZgpKUHoxdG9WdytLMTZZV2lPeE1IRUs0SXVaZ0o3SHVlTjNkT3loQmxIUFljUnVxZDdlWkhtWEpjdWNPTnNjVHBsCldkM0REb3FlSGVUWGFqTFFpVWIxemJZT2h3WFhJejJYVDZ6TU8vVUNnWUIwZU1pbnl4SDIyUnNVMUprcnlHYTcKMXVOMWdhcjZDazdCanFWRVhQOStYOVY1cC8vNk1xenRXSlhnY3NUaUNDN1ZCWnNsREU5Y3B4Yk5jYjNGWEhkagp5dWdGVzFqL21KMHNqcUFTM1ZSakpqbHlZMngvenplaWlLUzBPQ2owQTJnYWdvVXhVWWdZeXIzUy9WNDdzN0VZClphSmEzL05peURiS09TSk5KUE1DMVFLQmdGSFRjaWpTdllxWWlmd2hKOGRSVHE0TXZTeFdkTW5Db2dzdjR6YzUKUmZiSGpYY2JPL2RYSEd2eEFUUTRTVWVBTUdhaVMvZ3g2Ym5PajMwU2FSR21TYkxmL2V4S0oreEkxMGlxR2JDdQo5Q1pJcm5UVzNzZ0o2c3lrZENFaktEZTZ1bmNNQnAvVG9nUXZZcStVOXZUUUQ2b0s5aW84WFhPUlQzdDNrSDlmCmY1aUJBb0dCQUpuYUdFV1hCQ01hTVpwdlVzeXlSOGhwazlVT2pQZHE4bjExcnpPYXlUM1U5NG5neGQ0ZHI5cGkKWmZzcUxPdy9zWlBwUm1TL1VlbDVrMkc2Mm1ZcFRyc0pEMCtTekZleTlGR203cDluejhrQmJ5SGFrQ2NadDNlUQo3aWpFWEJOclpxdnBHQzNUUGVHQzFSeEJrRVlsYzlnMWJpcTczS0lmNlhvREVJamRFZUZsCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
        - name: clientCertificateData
          value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lJQjF5ZDF0KzBpb013RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRBek1qVXdOVFF3TkROYUZ3MHlNakF6TWpVd05UUXdORFJhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBZT3FBWkNoaEd6WkxCckEKTVBqTC9WZm9yWWNiWHlQd3pNTUhLM1hVQU9PMEo2cHZoajNPWXdxTDlXTy84RmpXbjVCWitYTmtVQW1qcSsxdApHQTZtQkpkR3FpN1J1Q0d6b09zT25ENGJGalg1Rlk4dHVsZVZ3cVVCUDRxLzF2OUZUVmgrTDg2a0pLZE50SEZrCmlyK0FMbW9Yd3JwZHhHZHM1MmFQems1aEFCT0NkbzN2NW5tMUlac2dGRmVlOThaeUREaUxwY2JvR0Z3RUV4aUUKOG5MYURhd2pMQTNtSzgvMWlZeTBXUG1yREczKzdqWFU2RnFsaGhDME9YU1BHamtFOGVEUHkwUTVyaUxiZTRDYwpaM2l4RGk1akdMekFRYkVFNU1xcnM1TkNSY05uQ2hVYnpOVUVYRzZUQmJ4YWJ0aFpUNWFGZUdmSG40eTd4RWtMCi9yNmZDUUlEQVFBQm8wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVUzUjVPNWVjNjZ6Y2ZjaFJJMDNEcVNnNjZ3eUl3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFHcGsyMUxsVWNxYXpkOTRUeXV5S2Q5cFAraG9JOXhELytwN3U5Rm5jV0xwbVZCN0tIQVpoYWRLCkZJaTdKM1UvRnE3Ykd5UlpLb1RzZFp4cVNrVm8xOXF3Mm1LVlYxandqZ3MwelZOZFowZVRsa3BUMHJKS0V5S3EKZVBOVUg4QU5VY2k0N0VGZVdVZGtJWUxpWVhOdzRLaFFFYkxmQm00aGNTOUlIaVN5V3hSaUFLSS9ZYlB2WnRnRwo3MmcwSEU1OFlFUWxZcjBIUjdZYWxlR0NVK2k4SnpUWDBjRFpEU1JyRjZqbFFpWm9jZU9lVmIvQ21YUFdhaHRFCkk3UVVabEhjWk5GT3RCbzI4N0JiNVBBaHJ4R2JpaThIdDFRWHRtWlpra3k0SWxlWlorVVF5R3ZTRVlVQWx3bjMKK09XVXBuN1ovdmdxUThKQ01uSW1OWldnNG5OMFF4Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    - name: deploy-image
      runAfter: [create-config]
      workspaces:
        - name: source
          workspace: sources
        - name: shared-workspace
          workspace: shared-workspace
      taskSpec:
        workspaces:
        - name: source
        - name: shared-workspace
        steps:
          - name: deploy
            image: gcr.io/cloud-builders/kubectl@sha256:8ab94be8b2b4f3d117f02d868b39540fddd225447abf4014f7ba4765cb39f753 
            script: |
              #!/usr/bin/env bash
              set -e
              ls -l 
              cd $(workspaces.source.path)/artifacts/
              
              export KUBECONFIG="$(workspaces.shared-workspace.path)/kubeconfig"
              kubectl create namespace tekton-deploy
              kubectl apply -f mathematicsCRD.yaml -n tekton-deploy
              kubectl apply -f deployment.yaml -n tekton-deploy
              
              
              
            