apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-events-triggertemplate
  namespace: tekton-events
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
    - name: project
      description: The name of the project.
  resourcetemplates: #PipelineRun defination starts below. Based on requirement resourcetemplates can contain any resource defination( like pipelineRun, taskRun)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        creationTimestamp: null
        generateName: $(tt.params.project)-
        namespace: $(tt.params.namespace)
      spec:
        params:
        - name: gitRepository
          value: $(tt.params.gitrepositoryurl) # here 'tt' means TriggerTemplate
        - name: gitRevision
          value: $(tt.params.gitrevision)
        pipelineRef:
          name: func-test-build-deploy-pipeline
        serviceAccountName: tekton-triggers-example-sa #this serviceAccount will be used for running pipeline. One pipeline Can have only one SA specified.
        workspaces:
        - name: sources #this workspace will be used to store project code
          persistentVolumeClaim:
            claimName: source-pvc
          subPath: source 
        - name: gitconfig #stores git secret
          secret:
            secretName: my-basic-auth-secret
        - name: dockerconfig #store docker secret
          secret:
            secretName: docker-auth-secret 
        - name: shared-workspace #this workspace will be used to store kubeconfig file
          persistentVolumeClaim:
            claimName: source-pvc
          subPath: config    
      status: {}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tekton-events-pipelinebinding
  namespace: tekton-events
spec:
  params: #Values from webhook payload JSON is used for filling below params.
    - name: gitrevision
      value: $(body.ref) #using body ref here. in place of it branch name, commit id, checkout_sha can also be used.
    - name: namespace
      value: tekton-events
    - name: gitrepositoryurl
      value: $(body.project.git_http_url)
    - name: project
      value: $(body.project.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-events-listener
  namespace: tekton-events
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: github-listener
      interceptors: #catches event and filters to check for which events pipeline should to be initiated.
      - gitlab:
          eventTypes: #specify event type to consider while initiating pipelineRun. If not provided, it will initiate pipeline for all eventtype.
          - Push Hook
      bindings:
      - ref: tekton-events-pipelinebinding
      template:
        ref: tekton-events-triggertemplate