apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-ingress-run
  namespace: tekton-events
spec:
  taskRef:
    name: create-ingress
  params:
  - name: CreateCertificate
    value: "false"
  - name: CertificateKeyPassphrase
    value: asecretphrase
  - name: CertificateSecretName
    value: ingresssecret
  - name: ExternalDomain
    value: eventlistner.chennaidev-26.tatacommunications.com
  - name: Service
    value: el-tekton-events-listener
  - name: ServicePort
    value: "8080"
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
