--- 
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: 
  creationTimestamp: null
  generateName: func-test-git-webhook-
  namespace: tekton-events
spec: 
  params: 
    - 
      name: gitRepository
      value: http://10.8.30.54:81/priya.kumari.Prject1
    - 
      name: gitRevision
      value: master
  pipelineRef: 
    name: func-test-build-deploy-pipeline
  serviceAccountName: tekton-triggers-example-sa
  workspaces: 
    - 
      name: sources
      persistentVolumeClaim: 
        claimName: source-pvc
      subPath: source
    - 
      name: gitconfig
      secret: 
        secretName: my-basic-auth-secret
status: {}
